#!/usr/bin/env bash
# Generate or update the NuraOS extlinux boot configuration.
#
# Reads the active slot from /data/etc/active-slot (or --slot) and writes
# extlinux.conf to BOOT_DIR with menu entries for:
#   - Active slot (default)
#   - Slot A
#   - Slot B
#   - Recovery mode
#
# Extra kernel options can be persisted in BOOT_DIR/cmdline.conf:
#   one option or option=value per line, # comments ignored.
#
# Usage:
#   ./scripts/boot-config.sh [OPTIONS]
#
# Options:
#   --slot a|b       force active slot (default: read from --data-dir/etc/active-slot)
#   --recovery       make recovery the default menu entry
#   --boot-dir PATH  directory where extlinux.conf is written (default: image/out/boot)
#   --data-dir PATH  path to /data root for reading active-slot (default: image/out/data-root)
#   --timeout N      boot menu timeout in tenths of a second (default: 50 = 5 s)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_DIR="${REPO_ROOT}/image/out"
BOOT_DIR="${OUT_DIR}/boot"
DATA_DIR="${OUT_DIR}/data-root"

SLOT=""
RECOVERY=0
MENU_TIMEOUT=50

while [[ $# -gt 0 ]]; do
    case "$1" in
        --slot)      shift; SLOT="$1" ;;
        --recovery)  RECOVERY=1 ;;
        --boot-dir)  shift; BOOT_DIR="$1" ;;
        --data-dir)  shift; DATA_DIR="$1" ;;
        --timeout)   shift; MENU_TIMEOUT="$1" ;;
        *) printf '[boot-config] unknown argument: %s\n' "$1" >&2; exit 1 ;;
    esac
    shift
done

log() { printf '[boot-config] %s\n' "$*"; }

mkdir -p "${BOOT_DIR}"

# Determine active slot.
ACTIVE_SLOT_FILE="${DATA_DIR}/etc/active-slot"
if [ -z "${SLOT}" ]; then
    if [ -f "${ACTIVE_SLOT_FILE}" ]; then
        SLOT=$(tr -d '[:space:]' < "${ACTIVE_SLOT_FILE}")
        log "read active slot from ${ACTIVE_SLOT_FILE}: ${SLOT}"
    else
        SLOT="a"
        log "active-slot file not found; defaulting to slot a"
    fi
fi
if [ "${SLOT}" != "a" ] && [ "${SLOT}" != "b" ]; then
    log "invalid slot '${SLOT}' (must be a or b); defaulting to a"
    SLOT="a"
fi

# Read persisted extra cmdline options (ignore blank lines and comments).
CMDLINE_CONF="${BOOT_DIR}/cmdline.conf"
EXTRA_CMDLINE=""
if [ -f "${CMDLINE_CONF}" ]; then
    EXTRA_CMDLINE=$(grep -v '^\s*#' "${CMDLINE_CONF}" | grep -v '^\s*$' | tr '\n' ' ' | sed 's/  */ /g;s/^ //;s/ $//')
fi

BASE="console=ttyS0,115200 panic=5 loglevel=7"

build_cmdline() {
    local slot="$1" recovery="$2"
    local line="${BASE} nura.slot=${slot}"
    [ "${recovery}" -eq 1 ] && line="${line} nura.recovery=1"
    [ -n "${EXTRA_CMDLINE}" ] && line="${line} ${EXTRA_CMDLINE}"
    printf '%s' "${line}"
}

CMDLINE_A=$(build_cmdline a 0)
CMDLINE_B=$(build_cmdline b 0)
CMDLINE_REC=$(build_cmdline "${SLOT}" 1)

if [ "${RECOVERY}" -eq 1 ]; then
    DEFAULT_LABEL="nura-recovery"
elif [ "${SLOT}" = "a" ]; then
    DEFAULT_LABEL="nura-slot-a"
else
    DEFAULT_LABEL="nura-slot-b"
fi

CONF_FILE="${BOOT_DIR}/extlinux.conf"

cat > "${CONF_FILE}" << EXTLINUX
# NuraOS extlinux boot configuration
# Generated by scripts/boot-config.sh -- do not edit by hand.
# To persist extra kernel options, edit ${CMDLINE_CONF}
# and re-run this script.
#
# Active slot: ${SLOT}  Recovery default: ${RECOVERY}

UI menu.c32
PROMPT 0
TIMEOUT ${MENU_TIMEOUT}
DEFAULT ${DEFAULT_LABEL}
MENU TITLE NuraOS Boot Menu

LABEL nura-slot-a
    MENU LABEL NuraOS -- Slot A$([ "${SLOT}" = "a" ] && printf " [active]")
    KERNEL /bzImage
    INITRD /initramfs.cpio.gz
    APPEND ${CMDLINE_A}

LABEL nura-slot-b
    MENU LABEL NuraOS -- Slot B$([ "${SLOT}" = "b" ] && printf " [active]")
    KERNEL /bzImage
    INITRD /initramfs.cpio.gz
    APPEND ${CMDLINE_B}

LABEL nura-recovery
    MENU LABEL NuraOS -- Recovery Mode (slot ${SLOT})
    KERNEL /bzImage
    INITRD /initramfs.cpio.gz
    APPEND ${RECOVERY_CMDLINE_PLACEHOLDER}
EXTLINUX

# Replace placeholder (avoid heredoc variable collision).
sed -i "s|RECOVERY_CMDLINE_PLACEHOLDER|${CMDLINE_REC}|" "${CONF_FILE}"

log "wrote ${CONF_FILE}"
log "default entry: ${DEFAULT_LABEL}"

# Create cmdline.conf template if absent.
if [ ! -f "${CMDLINE_CONF}" ]; then
    cat > "${CMDLINE_CONF}" << 'EOF'
# NuraOS persistent kernel command-line options.
# One option or option=value per line. Lines starting with # are ignored.
# These are appended to every boot menu entry.
# Examples:
#   quiet
#   nura.debug=1
EOF
    log "created ${CMDLINE_CONF} (add extra options here)"
fi
